//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Service.TanqueServiceHost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TanqueServiceHost.ITanqueService")]
    public interface ITanqueService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITanqueService/Inserir", ReplyAction="http://tempuri.org/ITanqueService/InserirResponse")]
        SP.Contract.Data.Tanque Inserir(SP.Contract.Data.Tanque _tanque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITanqueService/BuscarTodos", ReplyAction="http://tempuri.org/ITanqueService/BuscarTodosResponse")]
        SP.Contract.Data.Tanque[] BuscarTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITanqueService/QtdeDisponivel", ReplyAction="http://tempuri.org/ITanqueService/QtdeDisponivelResponse")]
        bool QtdeDisponivel(int codigo, int quantidade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITanqueServiceChannel : SP.Service.TanqueServiceHost.ITanqueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TanqueServiceClient : System.ServiceModel.ClientBase<SP.Service.TanqueServiceHost.ITanqueService>, SP.Service.TanqueServiceHost.ITanqueService {
        
        public TanqueServiceClient() {
        }
        
        public TanqueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TanqueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TanqueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TanqueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SP.Contract.Data.Tanque Inserir(SP.Contract.Data.Tanque _tanque) {
            return base.Channel.Inserir(_tanque);
        }
        
        public SP.Contract.Data.Tanque[] BuscarTodos() {
            return base.Channel.BuscarTodos();
        }
        
        public bool QtdeDisponivel(int codigo, int quantidade) {
            return base.Channel.QtdeDisponivel(codigo, quantidade);
        }
    }
}
