//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SP.Entities
{
    public partial class cliente
    {
        #region Primitive Properties
    
        public virtual string cpf
        {
            get;
            set;
        }
    
        public virtual string endereco
        {
            get;
            set;
        }
    
        public virtual string cep
        {
            get;
            set;
        }
    
        public virtual string cidade
        {
            get;
            set;
        }
    
        public virtual Nullable<int> num
        {
            get;
            set;
        }
    
        public virtual string fonecelular
        {
            get;
            set;
        }
    
        public virtual string fonecomercial
        {
            get;
            set;
        }
    
        public virtual string foneresidencial
        {
            get;
            set;
        }
    
        public virtual string nome
        {
            get;
            set;
        }
    
        public virtual string rg
        {
            get;
            set;
        }
    
        public virtual bool ativo
        {
            get;
            set;
        }
    
        public virtual int Cliente_ID
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<venda> venda
        {
            get
            {
                if (_venda == null)
                {
                    var newCollection = new FixupCollection<venda>();
                    newCollection.CollectionChanged += Fixupvenda;
                    _venda = newCollection;
                }
                return _venda;
            }
            set
            {
                if (!ReferenceEquals(_venda, value))
                {
                    var previousValue = _venda as FixupCollection<venda>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupvenda;
                    }
                    _venda = value;
                    var newValue = value as FixupCollection<venda>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupvenda;
                    }
                }
            }
        }
        private ICollection<venda> _venda;

        #endregion
        #region Association Fixup
    
        private void Fixupvenda(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (venda item in e.NewItems)
                {
                    item.cliente = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (venda item in e.OldItems)
                {
                    if (ReferenceEquals(item.cliente, this))
                    {
                        item.cliente = null;
                    }
                }
            }
        }

        #endregion
    }
}
