//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SP.Entities
{
    public partial class compra
    {
        #region Primitive Properties
    
        public virtual System.DateTime dataEmissao
        {
            get;
            set;
        }
    
        public virtual System.DateTime dataEntrada
        {
            get;
            set;
        }
    
        public virtual string serie
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> desconto
        {
            get;
            set;
        }
    
        public virtual decimal totalValorCompra
        {
            get;
            set;
        }
    
        public virtual int Compra_ID
        {
            get;
            set;
        }
    
        public virtual int Fornecedor_ID
        {
            get { return _fornecedor_ID; }
            set
            {
                if (_fornecedor_ID != value)
                {
                    if (fornecedor != null && fornecedor.Fornecedor_ID != value)
                    {
                        fornecedor = null;
                    }
                    _fornecedor_ID = value;
                }
            }
        }
        private int _fornecedor_ID;

        #endregion
        #region Navigation Properties
    
        public virtual fornecedor fornecedor
        {
            get { return _fornecedor; }
            set
            {
                if (!ReferenceEquals(_fornecedor, value))
                {
                    var previousValue = _fornecedor;
                    _fornecedor = value;
                    Fixupfornecedor(previousValue);
                }
            }
        }
        private fornecedor _fornecedor;
    
        public virtual ICollection<itemcompra> itemcompra
        {
            get
            {
                if (_itemcompra == null)
                {
                    var newCollection = new FixupCollection<itemcompra>();
                    newCollection.CollectionChanged += Fixupitemcompra;
                    _itemcompra = newCollection;
                }
                return _itemcompra;
            }
            set
            {
                if (!ReferenceEquals(_itemcompra, value))
                {
                    var previousValue = _itemcompra as FixupCollection<itemcompra>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupitemcompra;
                    }
                    _itemcompra = value;
                    var newValue = value as FixupCollection<itemcompra>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupitemcompra;
                    }
                }
            }
        }
        private ICollection<itemcompra> _itemcompra;

        #endregion
        #region Association Fixup
    
        private void Fixupfornecedor(fornecedor previousValue)
        {
            if (previousValue != null && previousValue.compra.Contains(this))
            {
                previousValue.compra.Remove(this);
            }
    
            if (fornecedor != null)
            {
                if (!fornecedor.compra.Contains(this))
                {
                    fornecedor.compra.Add(this);
                }
                if (Fornecedor_ID != fornecedor.Fornecedor_ID)
                {
                    Fornecedor_ID = fornecedor.Fornecedor_ID;
                }
            }
        }
    
        private void Fixupitemcompra(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (itemcompra item in e.NewItems)
                {
                    item.compra = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (itemcompra item in e.OldItems)
                {
                    if (ReferenceEquals(item.compra, this))
                    {
                        item.compra = null;
                    }
                }
            }
        }

        #endregion
    }
}
