//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SP.Entities
{
    public partial class itemvenda
    {
        #region Primitive Properties
    
        public virtual int ItemVenda_ID
        {
            get;
            set;
        }
    
        public virtual decimal preco
        {
            get;
            set;
        }
    
        public virtual Nullable<int> quantidade
        {
            get;
            set;
        }
    
        public virtual int Venda_ID
        {
            get { return _venda_ID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_venda_ID != value)
                    {
                        if (venda != null && venda.Venda_ID != value)
                        {
                            venda = null;
                        }
                        _venda_ID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _venda_ID;
    
        public virtual int Produto_ID
        {
            get { return _produto_ID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_produto_ID != value)
                    {
                        if (produto != null && produto.Produto_ID != value)
                        {
                            produto = null;
                        }
                        _produto_ID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _produto_ID;
    
        public virtual Nullable<int> Bomba_ID
        {
            get { return _bomba_ID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_bomba_ID != value)
                    {
                        if (bomba != null && bomba.Bomba_ID != value)
                        {
                            bomba = null;
                        }
                        _bomba_ID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _bomba_ID;

        #endregion
        #region Navigation Properties
    
        public virtual bomba bomba
        {
            get { return _bomba; }
            set
            {
                if (!ReferenceEquals(_bomba, value))
                {
                    var previousValue = _bomba;
                    _bomba = value;
                    Fixupbomba(previousValue);
                }
            }
        }
        private bomba _bomba;
    
        public virtual produto produto
        {
            get { return _produto; }
            set
            {
                if (!ReferenceEquals(_produto, value))
                {
                    var previousValue = _produto;
                    _produto = value;
                    Fixupproduto(previousValue);
                }
            }
        }
        private produto _produto;
    
        public virtual venda venda
        {
            get { return _venda; }
            set
            {
                if (!ReferenceEquals(_venda, value))
                {
                    var previousValue = _venda;
                    _venda = value;
                    Fixupvenda(previousValue);
                }
            }
        }
        private venda _venda;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixupbomba(bomba previousValue)
        {
            if (previousValue != null && previousValue.itemvenda.Contains(this))
            {
                previousValue.itemvenda.Remove(this);
            }
    
            if (bomba != null)
            {
                if (!bomba.itemvenda.Contains(this))
                {
                    bomba.itemvenda.Add(this);
                }
                if (Bomba_ID != bomba.Bomba_ID)
                {
                    Bomba_ID = bomba.Bomba_ID;
                }
            }
            else if (!_settingFK)
            {
                Bomba_ID = null;
            }
        }
    
        private void Fixupproduto(produto previousValue)
        {
            if (previousValue != null && previousValue.itemvenda.Contains(this))
            {
                previousValue.itemvenda.Remove(this);
            }
    
            if (produto != null)
            {
                if (!produto.itemvenda.Contains(this))
                {
                    produto.itemvenda.Add(this);
                }
                if (Produto_ID != produto.Produto_ID)
                {
                    Produto_ID = produto.Produto_ID;
                }
            }
        }
    
        private void Fixupvenda(venda previousValue)
        {
            if (previousValue != null && previousValue.itemvenda.Contains(this))
            {
                previousValue.itemvenda.Remove(this);
            }
    
            if (venda != null)
            {
                if (!venda.itemvenda.Contains(this))
                {
                    venda.itemvenda.Add(this);
                }
                if (Venda_ID != venda.Venda_ID)
                {
                    Venda_ID = venda.Venda_ID;
                }
            }
        }

        #endregion
    }
}
