//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SP.Entities
{
    public partial class itemcompra
    {
        #region Primitive Properties
    
        public virtual int ItemCompra_ID
        {
            get;
            set;
        }
    
        public virtual decimal preco
        {
            get;
            set;
        }
    
        public virtual int quantidade
        {
            get;
            set;
        }
    
        public virtual int Compra_ID
        {
            get { return _compra_ID; }
            set
            {
                if (_compra_ID != value)
                {
                    if (compra != null && compra.Compra_ID != value)
                    {
                        compra = null;
                    }
                    _compra_ID = value;
                }
            }
        }
        private int _compra_ID;
    
        public virtual int Produto_ID
        {
            get { return _produto_ID; }
            set
            {
                if (_produto_ID != value)
                {
                    if (produto != null && produto.Produto_ID != value)
                    {
                        produto = null;
                    }
                    _produto_ID = value;
                }
            }
        }
        private int _produto_ID;

        #endregion
        #region Navigation Properties
    
        public virtual compra compra
        {
            get { return _compra; }
            set
            {
                if (!ReferenceEquals(_compra, value))
                {
                    var previousValue = _compra;
                    _compra = value;
                    Fixupcompra(previousValue);
                }
            }
        }
        private compra _compra;
    
        public virtual produto produto
        {
            get { return _produto; }
            set
            {
                if (!ReferenceEquals(_produto, value))
                {
                    var previousValue = _produto;
                    _produto = value;
                    Fixupproduto(previousValue);
                }
            }
        }
        private produto _produto;

        #endregion
        #region Association Fixup
    
        private void Fixupcompra(compra previousValue)
        {
            if (previousValue != null && previousValue.itemcompra.Contains(this))
            {
                previousValue.itemcompra.Remove(this);
            }
    
            if (compra != null)
            {
                if (!compra.itemcompra.Contains(this))
                {
                    compra.itemcompra.Add(this);
                }
                if (Compra_ID != compra.Compra_ID)
                {
                    Compra_ID = compra.Compra_ID;
                }
            }
        }
    
        private void Fixupproduto(produto previousValue)
        {
            if (previousValue != null && previousValue.itemcompra.Contains(this))
            {
                previousValue.itemcompra.Remove(this);
            }
    
            if (produto != null)
            {
                if (!produto.itemcompra.Contains(this))
                {
                    produto.itemcompra.Add(this);
                }
                if (Produto_ID != produto.Produto_ID)
                {
                    Produto_ID = produto.Produto_ID;
                }
            }
        }

        #endregion
    }
}
