//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SP.Entities
{
    public partial class tanque
    {
        #region Primitive Properties
    
        public virtual string descricao
        {
            get;
            set;
        }
    
        public virtual int capacidade
        {
            get;
            set;
        }
    
        public virtual int Tanque_ID
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<bomba> bomba
        {
            get
            {
                if (_bomba == null)
                {
                    var newCollection = new FixupCollection<bomba>();
                    newCollection.CollectionChanged += Fixupbomba;
                    _bomba = newCollection;
                }
                return _bomba;
            }
            set
            {
                if (!ReferenceEquals(_bomba, value))
                {
                    var previousValue = _bomba as FixupCollection<bomba>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupbomba;
                    }
                    _bomba = value;
                    var newValue = value as FixupCollection<bomba>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupbomba;
                    }
                }
            }
        }
        private ICollection<bomba> _bomba;

        #endregion
        #region Association Fixup
    
        private void Fixupbomba(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (bomba item in e.NewItems)
                {
                    item.tanque = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (bomba item in e.OldItems)
                {
                    if (ReferenceEquals(item.tanque, this))
                    {
                        item.tanque = null;
                    }
                }
            }
        }

        #endregion
    }
}
