//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SP.Entities
{
    public partial class usuario
    {
        #region Primitive Properties
    
        public virtual string senha
        {
            get;
            set;
        }
    
        public virtual string usuario1
        {
            get;
            set;
        }
    
        public virtual int Usuario_ID
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<venda> venda
        {
            get
            {
                if (_venda == null)
                {
                    var newCollection = new FixupCollection<venda>();
                    newCollection.CollectionChanged += Fixupvenda;
                    _venda = newCollection;
                }
                return _venda;
            }
            set
            {
                if (!ReferenceEquals(_venda, value))
                {
                    var previousValue = _venda as FixupCollection<venda>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupvenda;
                    }
                    _venda = value;
                    var newValue = value as FixupCollection<venda>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupvenda;
                    }
                }
            }
        }
        private ICollection<venda> _venda;

        #endregion
        #region Association Fixup
    
        private void Fixupvenda(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (venda item in e.NewItems)
                {
                    item.usuario = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (venda item in e.OldItems)
                {
                    if (ReferenceEquals(item.usuario, this))
                    {
                        item.usuario = null;
                    }
                }
            }
        }

        #endregion
    }
}
