//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SP.Entities
{
    public partial class venda
    {
        #region Primitive Properties
    
        public virtual System.DateTime dataEmissao
        {
            get;
            set;
        }
    
        public virtual System.DateTime dataSaida
        {
            get;
            set;
        }
    
        public virtual string serie
        {
            get;
            set;
        }
    
        public virtual decimal totalDesconto
        {
            get;
            set;
        }
    
        public virtual int Venda_ID
        {
            get;
            set;
        }
    
        public virtual int Cliente_ID
        {
            get { return _cliente_ID; }
            set
            {
                if (_cliente_ID != value)
                {
                    if (cliente != null && cliente.Cliente_ID != value)
                    {
                        cliente = null;
                    }
                    _cliente_ID = value;
                }
            }
        }
        private int _cliente_ID;
    
        public virtual int Usuário_ID
        {
            get { return _usuário_ID; }
            set
            {
                if (_usuário_ID != value)
                {
                    if (usuario != null && usuario.Usuario_ID != value)
                    {
                        usuario = null;
                    }
                    _usuário_ID = value;
                }
            }
        }
        private int _usuário_ID;

        #endregion
        #region Navigation Properties
    
        public virtual cliente cliente
        {
            get { return _cliente; }
            set
            {
                if (!ReferenceEquals(_cliente, value))
                {
                    var previousValue = _cliente;
                    _cliente = value;
                    Fixupcliente(previousValue);
                }
            }
        }
        private cliente _cliente;
    
        public virtual ICollection<itemvenda> itemvenda
        {
            get
            {
                if (_itemvenda == null)
                {
                    var newCollection = new FixupCollection<itemvenda>();
                    newCollection.CollectionChanged += Fixupitemvenda;
                    _itemvenda = newCollection;
                }
                return _itemvenda;
            }
            set
            {
                if (!ReferenceEquals(_itemvenda, value))
                {
                    var previousValue = _itemvenda as FixupCollection<itemvenda>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupitemvenda;
                    }
                    _itemvenda = value;
                    var newValue = value as FixupCollection<itemvenda>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupitemvenda;
                    }
                }
            }
        }
        private ICollection<itemvenda> _itemvenda;
    
        public virtual usuario usuario
        {
            get { return _usuario; }
            set
            {
                if (!ReferenceEquals(_usuario, value))
                {
                    var previousValue = _usuario;
                    _usuario = value;
                    Fixupusuario(previousValue);
                }
            }
        }
        private usuario _usuario;

        #endregion
        #region Association Fixup
    
        private void Fixupcliente(cliente previousValue)
        {
            if (previousValue != null && previousValue.venda.Contains(this))
            {
                previousValue.venda.Remove(this);
            }
    
            if (cliente != null)
            {
                if (!cliente.venda.Contains(this))
                {
                    cliente.venda.Add(this);
                }
                if (Cliente_ID != cliente.Cliente_ID)
                {
                    Cliente_ID = cliente.Cliente_ID;
                }
            }
        }
    
        private void Fixupusuario(usuario previousValue)
        {
            if (previousValue != null && previousValue.venda.Contains(this))
            {
                previousValue.venda.Remove(this);
            }
    
            if (usuario != null)
            {
                if (!usuario.venda.Contains(this))
                {
                    usuario.venda.Add(this);
                }
                if (Usuário_ID != usuario.Usuario_ID)
                {
                    Usuário_ID = usuario.Usuario_ID;
                }
            }
        }
    
        private void Fixupitemvenda(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (itemvenda item in e.NewItems)
                {
                    item.venda = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (itemvenda item in e.OldItems)
                {
                    if (ReferenceEquals(item.venda, this))
                    {
                        item.venda = null;
                    }
                }
            }
        }

        #endregion
    }
}
