//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace SP.Entities
{
    public partial class SOSPostoDataContext : ObjectContext
    {
        public const string ConnectionString = "name=SOSPostoDataContext";
        public const string ContainerName = "SOSPostoDataContext";
    
        #region Constructors
    
        public SOSPostoDataContext()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public SOSPostoDataContext(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public SOSPostoDataContext(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<bomba> bomba
        {
            get { return _bomba  ?? (_bomba = CreateObjectSet<bomba>("bomba")); }
        }
        private ObjectSet<bomba> _bomba;
    
        public ObjectSet<cliente> cliente
        {
            get { return _cliente  ?? (_cliente = CreateObjectSet<cliente>("cliente")); }
        }
        private ObjectSet<cliente> _cliente;
    
        public ObjectSet<compra> compra
        {
            get { return _compra  ?? (_compra = CreateObjectSet<compra>("compra")); }
        }
        private ObjectSet<compra> _compra;
    
        public ObjectSet<fornecedor> fornecedor
        {
            get { return _fornecedor  ?? (_fornecedor = CreateObjectSet<fornecedor>("fornecedor")); }
        }
        private ObjectSet<fornecedor> _fornecedor;
    
        public ObjectSet<itemcompra> itemcompra
        {
            get { return _itemcompra  ?? (_itemcompra = CreateObjectSet<itemcompra>("itemcompra")); }
        }
        private ObjectSet<itemcompra> _itemcompra;
    
        public ObjectSet<itemvenda> itemvenda
        {
            get { return _itemvenda  ?? (_itemvenda = CreateObjectSet<itemvenda>("itemvenda")); }
        }
        private ObjectSet<itemvenda> _itemvenda;
    
        public ObjectSet<produto> produto
        {
            get { return _produto  ?? (_produto = CreateObjectSet<produto>("produto")); }
        }
        private ObjectSet<produto> _produto;
    
        public ObjectSet<tanque> tanque
        {
            get { return _tanque  ?? (_tanque = CreateObjectSet<tanque>("tanque")); }
        }
        private ObjectSet<tanque> _tanque;
    
        public ObjectSet<usuario> usuario
        {
            get { return _usuario  ?? (_usuario = CreateObjectSet<usuario>("usuario")); }
        }
        private ObjectSet<usuario> _usuario;
    
        public ObjectSet<venda> venda
        {
            get { return _venda  ?? (_venda = CreateObjectSet<venda>("venda")); }
        }
        private ObjectSet<venda> _venda;

        #endregion
    }
}
