//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Service.BombaServiceHost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BombaServiceHost.IBombaService")]
    public interface IBombaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBombaService/Buscar", ReplyAction="http://tempuri.org/IBombaService/BuscarResponse")]
        SP.Contract.Data.Bomba Buscar(int numeroBomba);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBombaService/LiberarAbastecimento", ReplyAction="http://tempuri.org/IBombaService/LiberarAbastecimentoResponse")]
        SP.Contract.Data.Bomba LiberarAbastecimento(int numeroBomba, int qtde, int tipoCombustivel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBombaServiceChannel : SP.Service.BombaServiceHost.IBombaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BombaServiceClient : System.ServiceModel.ClientBase<SP.Service.BombaServiceHost.IBombaService>, SP.Service.BombaServiceHost.IBombaService {
        
        public BombaServiceClient() {
        }
        
        public BombaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BombaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BombaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BombaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SP.Contract.Data.Bomba Buscar(int numeroBomba) {
            return base.Channel.Buscar(numeroBomba);
        }
        
        public SP.Contract.Data.Bomba LiberarAbastecimento(int numeroBomba, int qtde, int tipoCombustivel) {
            return base.Channel.LiberarAbastecimento(numeroBomba, qtde, tipoCombustivel);
        }
    }
}
